services:
  web:
    image: vladislav1234512345/morfix-django-restapi:1.3.35
    command: >
      sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 morfix_django_restapi.asgi:application"
    volumes:
      - /usr/src/app/static:/usr/src/app/static
      - /usr/src/app/media:/usr/src/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    image: vladislav1234512345/morfix-django-restapi:1.3.35
    command: >
      sh -c "celery -A morfix_django_restapi worker --loglevel=info --uid=nobody"
    environment:
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery-beat:
    image: vladislav1234512345/morfix-django-restapi:1.3.35
    command: >
      sh -c "celery -A morfix_django_restapi beat --loglevel=info"
    environment:
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery

#  nginx:
#    build: ./nginx
#    volumes:
#      - static_volume:/usr/src/app/static
#      - media_volume:/usr/src/app/media
#    ports:
#      - "8080:8080"
#    depends_on:
#      - web

volumes:
  postgres_data:
  redis_data:
