services:
  web:
    image: vladislav1234512345/morfix-django-restapi:1.2.6
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_NAME=morfix_django_restapi
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres
    environment:
      POSTGRES_DB: morfix_django_restapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    image: vladislav1234512345/morfix-django-restapi:1.2.6
    command: >
      sh -c "celery -A morfix_django_restapi worker --loglevel=info --uid=nobody"
    environment:
      - DEBUG=1
      - DB_NAME=morfix_django_restapi
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

  celery-beat:
    image: vladislav1234512345/morfix-django-restapi:1.2.6
    command: >
      sh -c "celery -A morfix_django_restapi beat --loglevel=info"
    environment:
      - DEBUG=1
      - DB_NAME=morfix_django_restapi
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
      - celery

volumes:
  postgres_data:
    external: true
  redis_data:
