# Generated by Django 5.1.1 on 2024-10-16 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilehobby',
            name='hobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hobby_profiles', to='profiles.hobby'),
        ),
        migrations.AddField(
            model_name='profilehobby',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_hobbies', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.ManyToManyField(related_name='profiles', through='profiles.ProfileHobby', to='profiles.hobby'),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='profiles.profile'),
        ),
    ]
