# Generated by Django 5.1.1 on 2024-10-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='is_profile_image',
            new_name='is_main_image',
        ),
    ]
