# Generated by Django 5.1.1 on 2024-10-14 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilehobby',
            name='hobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hobby_profiles', to='profiles.hobby'),
        ),
        migrations.AlterField(
            model_name='profilehobby',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_hobbies', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='profiles.profile'),
        ),
    ]
